### ISSUE TITLE
GraphQL Portal Roadmap: Q1-2 2021

### ISSUE THREAD

**Issue by valcker** [GraphQL-Portal/graphql-portal#223]
# Roadmap Overview

This roadmap is meant to us (users and the team) visibility over our priorities for the first part of the year. It is not meant to be fixed and is highly influenced by our users, so don't hesitate to comment on this!

From a high-level perspective, we are focusing on the following goals:
* **Approachability** – bring GraphQL to every home
* **Unified graph** – query all your data sources through one GraphQL API
* **Ease of use** and UX

The _how_ is broken down into the following steps:
- [ ] Stabilize the base data connector interface
- [ ] Schema extensions with good UX
- [ ] Type merging with good UX
- [ ] SaaS version
- [ ] Basic performance metrics
- [ ] Basic tracing support
- [ ] Single-image lightweight Dockerfile
- [ ] Improved documentation
- [ ] Better first-time user experience for GitHub repository and documentation
- [ ] Adding 50 new connectors
- [ ] Cache invalidation via triggers
